[project]
name = "slack-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai-slim[openai]>=1.0.0",
    "pydantic-settings>=2.10.1",
    "redis[hiredis]>=6.4.0",
    "slack-bolt>=1.23.0",
]
