services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 2
    volumes:
      - ./sample_data/superhero.sqlite:/var/lib/postgresql/data
    ports:
      - 5432:5432
  vector_db:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD: password
      - discovery.type: single-node
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    ports:
      - 9200:9200